name: Create data asset

on:
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: debug ls
      run: ls -lah experimentation/data/
    - name: debug pwd
      run: pwd
    - name: debug ls glob
      run: ls -lah /home/runner/work/mslearn-mlops/mslearn-mlops/experimentation/data
    - name: Create data asset
      run: |
        az ml data create --file src/data.yml \
        -g learning -w mslearn


